export enum ElectronStoreKeys {
	AppLanguage = 'appLanguage',
	IsNotFirstTimeAppStart = 'isNotFirstTimeAppStart',
	LastDesktopCapturerSourceId = 'lastDesktopCapturerSourceId',
	MuteMacSpeakersWhileCasting = 'muteMacSpeakersWhileCasting',
	AllowTabletControlWhileCasting = 'allowTabletControlWhileCasting',
	YouTubeKaraokeActive = 'youtubeKaraokeActive',
	YouTubeDjPlaylistModeEnabled = 'youtubeDjPlaylistModeEnabled',
	YouTubeDjCentralPlaylistId = 'youtubeDjCentralPlaylistId',
	YouTubeDjCentralPlaylistUrl = 'youtubeDjCentralPlaylistUrl',
	YouTubeDjSyncedVideoIds = 'youtubeDjSyncedVideoIds',
	YouTubeDjPlaylistLastSyncAt = 'youtubeDjPlaylistLastSyncAt',
	YouTubeDjPlaylistLastSyncError = 'youtubeDjPlaylistLastSyncError',
	YouTubeDjApiKey = 'youtubeDjApiKey',
}
